// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/objectbox_chunk.dart';
import 'data/models/objectbox_document.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5752376948486632411),
      name: 'ObjectBoxChunk',
      lastPropertyId: const obx_int.IdUid(7, 7098043879795265361),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4217316305337645588),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 93484344158144663),
            name: 'documentId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(1, 7624344973327968582)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9182622059443275615),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8534437329219131233),
            name: 'pageNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3242493948771489385),
            name: 'position',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2094643606052671253),
            name: 'embedding',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7098043879795265361),
            name: 'createdAt',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5498315713320911215),
      name: 'ObjectBoxDocument',
      lastPropertyId: const obx_int.IdUid(8, 2191930345903969694),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8377768547457799204),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8017336093586883171),
            name: 'documentId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(2, 5046353204677322969)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3139375862999256611),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 683684820295067005),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3115022755464442768),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8335064291106861995),
            name: 'createdAt',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 173305646034291062),
            name: 'pageCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2191930345903969694),
            name: 'thumbnailPath',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 5498315713320911215),
      lastIndexId: const obx_int.IdUid(2, 5046353204677322969),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ObjectBoxChunk: obx_int.EntityDefinition<ObjectBoxChunk>(
        model: _entities[0],
        toOneRelations: (ObjectBoxChunk object) => [],
        toManyRelations: (ObjectBoxChunk object) => {},
        getId: (ObjectBoxChunk object) => object.id,
        setId: (ObjectBoxChunk object, int id) {
          object.id = id;
        },
        objectToFB: (ObjectBoxChunk object, fb.Builder fbb) {
          final documentIdOffset = fbb.writeString(object.documentId);
          final contentOffset = fbb.writeString(object.content);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListInt8(object.embedding!);
          final createdAtOffset = fbb.writeString(object.createdAt);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, documentIdOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addInt64(3, object.pageNumber);
          fbb.addInt64(4, object.position);
          fbb.addOffset(5, embeddingOffset);
          fbb.addOffset(6, createdAtOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final documentIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final pageNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final positionParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final embeddingParam =
              const fb.ListReader<int>(fb.Int8Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 14);
          final createdAtParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = ObjectBoxChunk(
              documentId: documentIdParam,
              content: contentParam,
              pageNumber: pageNumberParam,
              position: positionParam,
              embedding: embeddingParam,
              createdAt: createdAtParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ObjectBoxDocument: obx_int.EntityDefinition<ObjectBoxDocument>(
        model: _entities[1],
        toOneRelations: (ObjectBoxDocument object) => [],
        toManyRelations: (ObjectBoxDocument object) => {},
        getId: (ObjectBoxDocument object) => object.id,
        setId: (ObjectBoxDocument object, int id) {
          object.id = id;
        },
        objectToFB: (ObjectBoxDocument object, fb.Builder fbb) {
          final documentIdOffset = fbb.writeString(object.documentId);
          final nameOffset = fbb.writeString(object.name);
          final pathOffset = fbb.writeString(object.path);
          final typeOffset = fbb.writeString(object.type);
          final createdAtOffset = fbb.writeString(object.createdAt);
          final thumbnailPathOffset = object.thumbnailPath == null
              ? null
              : fbb.writeString(object.thumbnailPath!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, documentIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, pathOffset);
          fbb.addOffset(4, typeOffset);
          fbb.addOffset(5, createdAtOffset);
          fbb.addInt64(6, object.pageCount);
          fbb.addOffset(7, thumbnailPathOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final documentIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final pathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final createdAtParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final pageCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final thumbnailPathParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 18);
          final object = ObjectBoxDocument(
              documentId: documentIdParam,
              name: nameParam,
              path: pathParam,
              type: typeParam,
              createdAt: createdAtParam,
              pageCount: pageCountParam,
              thumbnailPath: thumbnailPathParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ObjectBoxChunk] entity fields to define ObjectBox queries.
class ObjectBoxChunk_ {
  /// see [ObjectBoxChunk.id]
  static final id =
      obx.QueryIntegerProperty<ObjectBoxChunk>(_entities[0].properties[0]);

  /// see [ObjectBoxChunk.documentId]
  static final documentId =
      obx.QueryStringProperty<ObjectBoxChunk>(_entities[0].properties[1]);

  /// see [ObjectBoxChunk.content]
  static final content =
      obx.QueryStringProperty<ObjectBoxChunk>(_entities[0].properties[2]);

  /// see [ObjectBoxChunk.pageNumber]
  static final pageNumber =
      obx.QueryIntegerProperty<ObjectBoxChunk>(_entities[0].properties[3]);

  /// see [ObjectBoxChunk.position]
  static final position =
      obx.QueryIntegerProperty<ObjectBoxChunk>(_entities[0].properties[4]);

  /// see [ObjectBoxChunk.embedding]
  static final embedding =
      obx.QueryByteVectorProperty<ObjectBoxChunk>(_entities[0].properties[5]);

  /// see [ObjectBoxChunk.createdAt]
  static final createdAt =
      obx.QueryStringProperty<ObjectBoxChunk>(_entities[0].properties[6]);
}

/// [ObjectBoxDocument] entity fields to define ObjectBox queries.
class ObjectBoxDocument_ {
  /// see [ObjectBoxDocument.id]
  static final id =
      obx.QueryIntegerProperty<ObjectBoxDocument>(_entities[1].properties[0]);

  /// see [ObjectBoxDocument.documentId]
  static final documentId =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[1]);

  /// see [ObjectBoxDocument.name]
  static final name =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[2]);

  /// see [ObjectBoxDocument.path]
  static final path =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[3]);

  /// see [ObjectBoxDocument.type]
  static final type =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[4]);

  /// see [ObjectBoxDocument.createdAt]
  static final createdAt =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[5]);

  /// see [ObjectBoxDocument.pageCount]
  static final pageCount =
      obx.QueryIntegerProperty<ObjectBoxDocument>(_entities[1].properties[6]);

  /// see [ObjectBoxDocument.thumbnailPath]
  static final thumbnailPath =
      obx.QueryStringProperty<ObjectBoxDocument>(_entities[1].properties[7]);
}
